version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8010:8010"
    container_name: ams
    volumes:
      - .:/app
    networks:
      - network
    # network_mode: "host"

networks:
  network:
    driver: bridge